// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: auth_sample.proto

#include "auth_sample.pb.h"
#include "auth_sample.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace grpc {
namespace testing {

static const char* TestService_method_names[] = {
  "/grpc.testing.TestService/UnaryCall",
};

std::unique_ptr< TestService::Stub> TestService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TestService::Stub> stub(new TestService::Stub(channel));
  return stub;
}

TestService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_UnaryCall_(TestService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TestService::Stub::UnaryCall(::grpc::ClientContext* context, const ::grpc::testing::Request& request, ::grpc::testing::Response* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UnaryCall_, context, request, response);
}

void TestService::Stub::experimental_async::UnaryCall(::grpc::ClientContext* context, const ::grpc::testing::Request* request, ::grpc::testing::Response* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UnaryCall_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::grpc::testing::Response>* TestService::Stub::AsyncUnaryCallRaw(::grpc::ClientContext* context, const ::grpc::testing::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc::testing::Response>::Create(channel_.get(), cq, rpcmethod_UnaryCall_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::grpc::testing::Response>* TestService::Stub::PrepareAsyncUnaryCallRaw(::grpc::ClientContext* context, const ::grpc::testing::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::grpc::testing::Response>::Create(channel_.get(), cq, rpcmethod_UnaryCall_, context, request, false);
}

TestService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TestService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TestService::Service, ::grpc::testing::Request, ::grpc::testing::Response>(
          std::mem_fn(&TestService::Service::UnaryCall), this)));
}

TestService::Service::~Service() {
}

::grpc::Status TestService::Service::UnaryCall(::grpc::ServerContext* context, const ::grpc::testing::Request* request, ::grpc::testing::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grpc
}  // namespace testing

