// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sdk2TrackingMqApi.proto

#include "Sdk2TrackingMqApi.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace pb {
class AdInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AdInfo>
      _instance;
} _AdInfo_default_instance_;
}  // namespace pb
namespace protobuf_Sdk2TrackingMqApi_2eproto {
static void InitDefaultsAdInfo() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pb::_AdInfo_default_instance_;
    new (ptr) ::pb::AdInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pb::AdInfo::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_AdInfo =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsAdInfo}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_AdInfo.base);
}

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::pb::AdInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::pb::AdInfo, appname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::pb::AdInfo, adspacename_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::pb::AdInfo)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::pb::_AdInfo_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "Sdk2TrackingMqApi.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\027Sdk2TrackingMqApi.proto\022\002pb\".\n\006AdInfo\022"
      "\017\n\007appName\030\001 \001(\t\022\023\n\013adSpaceName\030\002 \001(\t*\236\001"
      "\n\010DataType\022\010\n\004NONE\020\000\022\017\n\013PLATFORM_AD\020\001\022\014\n"
      "\010VIDEO_AD\020\002\022\n\n\006OWN_AD\020\003\022\016\n\nDOU_YIN_AD\020\004\022"
      "\n\n\006UN_HIT\020\005\022\016\n\nLIMIT_TIME\020\006\022\017\n\013LOGIC_ERR"
      "OR\020\007\022\017\n\013LOCK_SCREEN\020\010\022\017\n\013GAME62_DATA\020\tB\002"
      "P\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 250);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Sdk2TrackingMqApi.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_Sdk2TrackingMqApi_2eproto
namespace pb {
const ::google::protobuf::EnumDescriptor* DataType_descriptor() {
  protobuf_Sdk2TrackingMqApi_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Sdk2TrackingMqApi_2eproto::file_level_enum_descriptors[0];
}
bool DataType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void AdInfo::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AdInfo::kAppNameFieldNumber;
const int AdInfo::kAdSpaceNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AdInfo::AdInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_Sdk2TrackingMqApi_2eproto::scc_info_AdInfo.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.AdInfo)
}
AdInfo::AdInfo(const AdInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  appname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.appname().size() > 0) {
    appname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.appname_);
  }
  adspacename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.adspacename().size() > 0) {
    adspacename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.adspacename_);
  }
  // @@protoc_insertion_point(copy_constructor:pb.AdInfo)
}

void AdInfo::SharedCtor() {
  appname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  adspacename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

AdInfo::~AdInfo() {
  // @@protoc_insertion_point(destructor:pb.AdInfo)
  SharedDtor();
}

void AdInfo::SharedDtor() {
  appname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  adspacename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void AdInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* AdInfo::descriptor() {
  ::protobuf_Sdk2TrackingMqApi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Sdk2TrackingMqApi_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AdInfo& AdInfo::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_Sdk2TrackingMqApi_2eproto::scc_info_AdInfo.base);
  return *internal_default_instance();
}


void AdInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.AdInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  appname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  adspacename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool AdInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.AdInfo)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string appName = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_appname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->appname().data(), static_cast<int>(this->appname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.AdInfo.appName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string adSpaceName = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_adspacename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->adspacename().data(), static_cast<int>(this->adspacename().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pb.AdInfo.adSpaceName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.AdInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.AdInfo)
  return false;
#undef DO_
}

void AdInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.AdInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string appName = 1;
  if (this->appname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->appname().data(), static_cast<int>(this->appname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.AdInfo.appName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->appname(), output);
  }

  // string adSpaceName = 2;
  if (this->adspacename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->adspacename().data(), static_cast<int>(this->adspacename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.AdInfo.adSpaceName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->adspacename(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:pb.AdInfo)
}

::google::protobuf::uint8* AdInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:pb.AdInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string appName = 1;
  if (this->appname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->appname().data(), static_cast<int>(this->appname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.AdInfo.appName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->appname(), target);
  }

  // string adSpaceName = 2;
  if (this->adspacename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->adspacename().data(), static_cast<int>(this->adspacename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pb.AdInfo.adSpaceName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->adspacename(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.AdInfo)
  return target;
}

size_t AdInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.AdInfo)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string appName = 1;
  if (this->appname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->appname());
  }

  // string adSpaceName = 2;
  if (this->adspacename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->adspacename());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AdInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.AdInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const AdInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AdInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.AdInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.AdInfo)
    MergeFrom(*source);
  }
}

void AdInfo::MergeFrom(const AdInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.AdInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.appname().size() > 0) {

    appname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.appname_);
  }
  if (from.adspacename().size() > 0) {

    adspacename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.adspacename_);
  }
}

void AdInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.AdInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AdInfo::CopyFrom(const AdInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.AdInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AdInfo::IsInitialized() const {
  return true;
}

void AdInfo::Swap(AdInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AdInfo::InternalSwap(AdInfo* other) {
  using std::swap;
  appname_.Swap(&other->appname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  adspacename_.Swap(&other->adspacename_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata AdInfo::GetMetadata() const {
  protobuf_Sdk2TrackingMqApi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Sdk2TrackingMqApi_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::pb::AdInfo* Arena::CreateMaybeMessage< ::pb::AdInfo >(Arena* arena) {
  return Arena::CreateInternal< ::pb::AdInfo >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
